seed_everything: null
trainer:
  logger: true
  max_epochs: 10
  accumulate_grad_batches: 1
model:
  backbone: swin_tiny_patch4_window7_224.ms_in1k
  num_classes: 10
  optimizer_kwargs:
    opt: sgd
    lr: 1e-5
    # wd: 0
    momentum: 0.9
  scheduler_kwargs:
    sched: cosine
    warmup_epochs: 1
data:
  class_path: GastroDataModule
  init_args:
    dataloader_kwargs:
      batch_size: 32
      num_workers: 2
      pin_memory: true
  # data_dir: ./