model:
  backbone: vit_small_patch16_224.augreg_in1k
  # backbone: swin_tiny_patch4_window7_224.ms_in1k
  # backbone: t2t_vit_14
  target_model:
    class_path: __main__.ClassifierFromLatestCheckpoint
    init_args:
      # path: saved_models/classifier/cifar10/v4/vit_small_patch16_224/
      # path: saved_models/classifier/cifar10/v4/swin_tiny_patch4_window7_224/
      # path: saved_models/classifier/cifar10/v4/t2t_vit_14/
      path: saved_models/classifier/gastro/v5/vit_small_patch16_224/
      # path: saved_models/classifier/gastro/v5/swin_tiny_patch4_window7_224/
      # path: saved_models/classifier/gastro/v5/t2t_vit_14/
  optimizer_kwargs:
    opt: adamw
    lr: 5.0e-05
    lr_head: 0.0002
    # opt: sgd
    # lr: 0.001
    # lr_head: 0.01
    # weight_decay: 5e-4
    # momentum: 0.9
  scheduler_kwargs:
    sched: cosine
    warmup_epochs: 1
    min_lr: 1e-6

data:
  wrapped_datamodule:
    # class_path: CIFAR10DataModule
    class_path: GastroDataModule
    init_args:
      cropped: true
  generate_masks_kwargs:
    num_players: 16
    num_mask_samples: 2
    paired_mask_samples: true
    mode: shapley
  dataloader_kwargs:
    batch_size: 128
    num_workers: 2
    pin_memory: true

trainer:
  max_epochs: 300  # ~30 for CIFAR10, ~200 for Gastro
  accumulate_grad_batches: 1

seed_everything: 3
